### ISSUE TITLE
Can't read big files

### ISSUE THREAD

**Issue by Tosible** [Starwarsfan2099/Python-Hash-Cracker#1]
When I try to use with the crackstation wordlist, the script doesn't work. I get no errors or anything. The crackstation is about 15+ GB in size

```
D:\Hashes>hashbrute.py -h 5f4dcc3b5aa765d61d8327deb882cf99 -t md5 -w crackstation.txt -v

Python Hash-Cracker
Version 3.0-2 Stable
[Running on Windows]

[*]Hash: 5f4dcc3b5aa765d61d8327deb882cf99
[*]Hash type: md5
[*]Wordlist: crackstation.txt
[+]Cracking...

[-]Hash not cracked:
[*]Reached end of wordlist
[*]Try another wordlist
[*]Words tryed: 0

D:\Hashes>

**Comment by Starwarsfan2099** [comment]
I updated it to work with a wider array of word lists. Some new line formatting was causing problems. Also fixed the scripts memory management to where it should work with any size file. I downloaded and tested the crackstation word list and it now works on my machine. Let me know if it works for you!

**Comment by Tosible** [comment]
Awesome, it works perfectly now! Many thanks!
